name: Auto add bump label

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-bump-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Remove label BUMPER (if exist)
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: bumped
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
      
      - name: Add bump label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: need-bump
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
