name: Auto add bump label

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-bump-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Add bump label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: bump